
package water.pollution.forms;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Panel;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import water.pollution.model.ConexaoDB;


public class Desktop extends javax.swing.JFrame {
        
    public Desktop() {
        initComponents();
        
        
        this.setTitle("Water Polution - Gerenciamento de Poluição de Rios");
        
        // Centro da tela
        this.setLocationRelativeTo(null);
        
        //Tamanho fixo da tela
        this.setResizable(false);
        
        //Ícone do título
        URL url = this.getClass().getResource("iconeTitulo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        
        // Abri a conexão
        ConexaoDB.OpenConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaFundo = new javax.swing.JPanel();
        gerencRios = new javax.swing.JButton();
        gerencPoluicao = new javax.swing.JButton();
        analiseRios = new javax.swing.JButton();
        fecharProgama = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        imagemTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);

        telaFundo.setBackground(new java.awt.Color(0, 0, 0));

        gerencRios.setBackground(new java.awt.Color(0, 51, 204));
        gerencRios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gerencRios.setForeground(new java.awt.Color(255, 255, 255));
        gerencRios.setText("Gerenciamento de Rios");
        gerencRios.setBorder(null);
        gerencRios.setPreferredSize(new java.awt.Dimension(143, 112));
        gerencRios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerencRiosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gerencRiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gerencRiosMouseExited(evt);
            }
        });
        gerencRios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerencRiosActionPerformed(evt);
            }
        });

        gerencPoluicao.setBackground(new java.awt.Color(0, 51, 204));
        gerencPoluicao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gerencPoluicao.setForeground(new java.awt.Color(255, 255, 255));
        gerencPoluicao.setText("Gerenciamento de Poluição");
        gerencPoluicao.setBorder(null);
        gerencPoluicao.setPreferredSize(new java.awt.Dimension(143, 112));
        gerencPoluicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerencPoluicaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gerencPoluicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gerencPoluicaoMouseExited(evt);
            }
        });
        gerencPoluicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerencPoluicaoActionPerformed(evt);
            }
        });

        analiseRios.setBackground(new java.awt.Color(0, 51, 204));
        analiseRios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        analiseRios.setForeground(new java.awt.Color(255, 255, 255));
        analiseRios.setText("Análise de Rios");
        analiseRios.setBorder(null);
        analiseRios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analiseRiosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                analiseRiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                analiseRiosMouseExited(evt);
            }
        });
        analiseRios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analiseRiosActionPerformed(evt);
            }
        });

        fecharProgama.setBackground(new java.awt.Color(255, 0, 0));
        fecharProgama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fecharProgama.setForeground(new java.awt.Color(255, 255, 255));
        fecharProgama.setText("Fechar Programa");
        fecharProgama.setBorder(null);
        fecharProgama.setPreferredSize(new java.awt.Dimension(143, 112));
        fecharProgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharProgamaActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("WATER POLLUTION");

        imagemTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/water/pollution/forms/iconeTitulo.png"))); // NOI18N
        imagemTitulo.setText("jLabel2");

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaFundoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(imagemTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(telaFundoLayout.createSequentialGroup()
                        .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gerencRios, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(analiseRios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerencPoluicao, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecharProgama, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 119, Short.MAX_VALUE))))
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaFundoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo)
                    .addComponent(imagemTitulo))
                .addGap(44, 44, 44)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerencRios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerencPoluicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analiseRios, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecharProgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analiseRiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analiseRiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analiseRiosActionPerformed

    private void gerencPoluicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerencPoluicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerencPoluicaoActionPerformed

    private void fecharProgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharProgamaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fecharProgamaActionPerformed

    private void gerencRiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerencRiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerencRiosActionPerformed

    private void gerencRiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerencRiosMouseEntered
        //Muda a cor do botão ao colocar o mouse
        gerencRios.setBackground(Color.green);
    }//GEN-LAST:event_gerencRiosMouseEntered

    private void gerencRiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerencRiosMouseExited
        //Volta a cor original do botão ao tirar o mouse
        gerencRios.setBackground(new java.awt.Color(0 , 51, 204));
    }//GEN-LAST:event_gerencRiosMouseExited

    private void gerencPoluicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerencPoluicaoMouseEntered
        //Muda a cor do botão ao colocar o mouse
        gerencPoluicao.setBackground(Color.green);
    }//GEN-LAST:event_gerencPoluicaoMouseEntered

    private void gerencPoluicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerencPoluicaoMouseExited
        //Volta a cor original do botão ao tirar o mouse
        gerencPoluicao.setBackground(new java.awt.Color(0 , 51, 204));
    }//GEN-LAST:event_gerencPoluicaoMouseExited

    private void analiseRiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analiseRiosMouseEntered
        //Muda a cor do botão ao colocar o mouse
        analiseRios.setBackground(Color.green);
    }//GEN-LAST:event_analiseRiosMouseEntered

    private void analiseRiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analiseRiosMouseExited
        //Volta a cor original do botão ao tirar o mouse
        analiseRios.setBackground(new java.awt.Color(0 , 51, 204));
    }//GEN-LAST:event_analiseRiosMouseExited

    private void gerencRiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerencRiosMouseClicked
        OpenForm(new GerenciamentoRio());        
    }//GEN-LAST:event_gerencRiosMouseClicked

    private void gerencPoluicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerencPoluicaoMouseClicked
        OpenForm(new GerenciamentoPoluicao());
    }//GEN-LAST:event_gerencPoluicaoMouseClicked

    private void analiseRiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analiseRiosMouseClicked
        OpenForm(new AnaliseRioPoluicao());
    }//GEN-LAST:event_analiseRiosMouseClicked

    private void OpenForm(JFrame form){
        form.setLocationRelativeTo(null);
        form.setVisible(true);

        //Ícone do título
        URL url = this.getClass().getResource("iconeTitulo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        form.setIconImage(iconeTitulo);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analiseRios;
    private javax.swing.JButton fecharProgama;
    private javax.swing.JButton gerencPoluicao;
    private javax.swing.JButton gerencRios;
    private javax.swing.JLabel imagemTitulo;
    private javax.swing.JPanel telaFundo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
