/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package water.pollution.forms;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import water.pollution.model.ConexaoDB;
import water.pollution.model.Entity.Rio;
import water.pollution.model.Entity.RioPoluicao;

/**
 *
 * @author willi
 */
public class GerenciamentoPoluicao extends javax.swing.JFrame {
    ArrayList<RioPoluicao> Dados = new ArrayList<RioPoluicao>();

    /**
     * Creates new form GerenciamentoRio
     */
    public GerenciamentoPoluicao() {
        initComponents();        
        // Para fechar apenas a propria tela no X
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        // Titulo do Form
        this.setTitle("Gerenciameto de poluição");
        
        // Centro da tela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_Alteracao = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Localizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Cadastrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Salvar alterações");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_Alteracao.setText("Alterar");
        btn_Alteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AlteracaoMouseClicked(evt);
            }
        });

        btn_Delete.setText("Excluir");
        btn_Delete.setToolTipText("");
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseClicked(evt);
            }
        });

        btn_Localizar.setText("Atualizar grade");
        btn_Localizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Localizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LocalizarMouseClicked(evt);
            }
        });
        btn_Localizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Alteracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Localizar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btn_Alteracao)
                    .addComponent(btn_Delete)
                    .addComponent(btn_Localizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTableRios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Id Rio", "Nome rio", "Id Poluição", "Nome poluição", "Ano", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRios);
        if (jTableRios.getColumnModel().getColumnCount() > 0) {
            jTableRios.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableRios.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarJTableFromDados(){
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableRios.getModel();
            
        // Limpando registros
        modeloTabela.setRowCount(0);
        
        for(RioPoluicao pol : this.Dados){
            modeloTabela.addRow(new Object[] {  
                pol._Id,
                pol.Fk_rio,
                pol.NomeRio,
                pol.Fk_tipopoluicao, 
                pol.NomeTipoPoluicao,
                pol.Ano,
                pol.Quantidade
            }); 
        }
        
        jTableRios.setModel(modeloTabela);
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        InfoRios cad = new InfoRios();
        cad.setVisible(true);
        
        cad.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if(cad.Data != null){
                    cad.Data.Acao = "I";
                    Dados.add(cad.Data);
                    AtualizarJTableFromDados();
                }                
            }
        });
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String SQL = ""; 
        for(RioPoluicao riop : this.Dados){
            try{
                switch(riop.Acao){
                    case "I":
                        /** Monta o Insert do RioPoluição */ 
                        SQL = "INSERT INTO RioPoluicao (FK_RIO, FK_TIPOPOLUICAO, Ano, Quantidade) VALUES ( ";
                        SQL += "    '" + riop.Fk_rio.toString() + "' ,";
                        SQL += "    '" + riop.Fk_tipopoluicao.toString() + "' ,";
                        SQL += "    '" + riop.Ano.toString() + "' ,";
                        SQL += "    '" + riop.Quantidade.toString() + "'  )";
                        PreparedStatement pstm = ConexaoDB.getNewPreparedStatement(SQL);
                        
                        pstm.execute();
                        pstm.close();
                        break;

                    case "A":
                        /** Monta o Update do RioPoluição */ 
                        String query = "UPDATE RIOPOLUICAO SET FK_RIO = ?, FK_TIPOPOLUICAO = ?, Ano = ?, Quantidade = ? WHERE _ID = ?";
                        pstm = ConexaoDB.getNewPreparedStatement(query);
                        
                        pstm.setInt(1, riop.Fk_rio);
                        pstm.setInt(2, riop.Fk_tipopoluicao);
                        pstm.setInt(3, riop.Ano);
                        pstm.setFloat(4, riop.Quantidade);
                        pstm.setInt(5, riop._Id);
                        
                        pstm.execute();
                        pstm.close();
                        break;

                    case "D":
                        /** Monta o Delete do RioPoluição */ 
                        SQL = "DELETE FROM RioPoluicao WHERE _ID = ?";
                        
                        pstm = ConexaoDB.getNewPreparedStatement(SQL);
                        pstm.setInt(1, riop._Id);
                        
                        pstm.execute();
                        pstm.close();
                        break;
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro na ação '"+ riop.Acao +"' da poluição.");
                return;
            }
        }
        
        JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso.");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_AlteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AlteracaoMouseClicked
        // TODO add your handling code here:
        if(jTableRios.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null,"Nenhum registro foi selecionado.");
            return;
        }
        
        InfoRios alt = new InfoRios();
        alt.Data = this.Dados.get(jTableRios.getSelectedRow());
        alt.setVisible(true);
        
        alt.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                AtualizarJTableFromDados();
            }
        });
    }//GEN-LAST:event_btn_AlteracaoMouseClicked

    private void btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseClicked
        if(jTableRios.getSelectedRow() < 0){
            return;
        }
        
        this.Dados.get(jTableRios.getSelectedRow()).Acao = "D";
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableRios.getModel();
        modeloTabela.removeRow(jTableRios.getSelectedRow());
    }//GEN-LAST:event_btn_DeleteMouseClicked

    private void btn_LocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LocalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LocalizarActionPerformed

    private void btn_LocalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LocalizarMouseClicked
        // PEga um rio qualquer

        try {
            PreparedStatement query = ConexaoDB.getNewPreparedStatement("SELECT * FROM VW_RIOPOLUICAO");
            ResultSet result = query.executeQuery();

            /** Montando JTable */
            DefaultTableModel modeloTabela = (DefaultTableModel) jTableRios.getModel();

            // Limpando registros
            modeloTabela.setRowCount(0);
            this.Dados.clear();

            while(result.next()) {
                modeloTabela.addRow(new Object[] {
                    String.valueOf(result.getInt("_ID")),
                    String.valueOf(result.getInt("IdRio")),
                    result.getString("NomeRio"),
                    String.valueOf(result.getInt("IdTipoPoluicao")),
                    result.getString("NomeTipoPoluicao"),
                    String.valueOf(result.getInt("Ano")),
                    result.getDouble("Quantidade")
                });

                RioPoluicao newDado = new RioPoluicao();
                newDado._Id = result.getInt("_ID");
                newDado.Fk_rio = result.getInt("IdRio");
                newDado.NomeRio = result.getString("NomeRio");
                newDado.Fk_tipopoluicao = result.getInt("IdTipoPoluicao");
                newDado.NomeTipoPoluicao = result.getString("NomeTipoPoluicao");
                newDado.Ano = result.getInt("Ano");
                newDado.Quantidade = result.getFloat("Quantidade");
                newDado.Acao = "";
                this.Dados.add(newDado);
            }

            jTableRios.setModel(modeloTabela);
            result.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar poluições.\n\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_LocalizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                    
                }
                
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoRio().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Alteracao;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Localizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRios;
    // End of variables declaration//GEN-END:variables
}
