/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package water.pollution.forms;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import water.pollution.model.ConexaoDB;
import water.pollution.model.Entity.Rio;

/**
 *
 * @author willi
 */
public class GerenciamentoRio extends javax.swing.JFrame {
    ArrayList<Rio> Dados = new ArrayList<Rio>();

    /**
     * Creates new form GerenciamentoRio
     */
    public GerenciamentoRio() {
        initComponents();        
        // Para fechar apenas a propria tela no X
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        //Titulo do form
        this.setTitle("Gerenciamento de rio");
        
        // Centro da tela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_Alteracao = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Localizar = new javax.swing.JButton();
        txt_Busca = new javax.swing.JTextField();
        ComboBoxFiltro = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setText("Cadastrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Salvar alterações");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_Alteracao.setText("Alterar");
        btn_Alteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AlteracaoMouseClicked(evt);
            }
        });

        btn_Delete.setText("Excluir");
        btn_Delete.setToolTipText("");
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseClicked(evt);
            }
        });

        btn_Localizar.setText("Localizar");
        btn_Localizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Localizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LocalizarMouseClicked(evt);
            }
        });
        btn_Localizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LocalizarActionPerformed(evt);
            }
        });

        txt_Busca.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        ComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tudo", "Nome", "ID" }));
        ComboBoxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Alteracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Delete)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txt_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(btn_Localizar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btn_Alteracao)
                    .addComponent(btn_Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBoxFiltro)
                        .addComponent(txt_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Localizar))
                .addContainerGap())
        );

        jTableRios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Localidade", "Nascente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRios);
        if (jTableRios.getColumnModel().getColumnCount() > 0) {
            jTableRios.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableRios.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LocalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LocalizarActionPerformed

    private void btn_LocalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LocalizarMouseClicked
        // PEga um rio qualquer

        try {
            // Essa é uma forma de realizar uma select
            //      
            
            // Essa é outra de realizar qualquer query (INSET, UPDATE, DELETE, SELECT)
            // podendo trocar parametros por valore para evitar SQLInject
            // OBS: Quando for INSER, DELETE ou UPDATE é importante fechar depois (query.close())
            
            String SQL, valorTroca = null;
            
            SQL = "SELECT * FROM RIO ";
            
            switch (ComboBoxFiltro.getSelectedIndex()) {
                case 0:
                    SQL += "";
                    valorTroca = "Tudo";
                    break;
                case 1:
                    SQL += " WHERE Nome = ?";
                    valorTroca = txt_Busca.getText();
                    break;
                case 2:
                    SQL += " WHERE _ID = ? ";
                    valorTroca = txt_Busca.getText();
                    break;
                default:
                    break;
            }
              
            PreparedStatement query = ConexaoDB.getNewPreparedStatement(SQL);
            
            if(valorTroca != "Tudo"){
                query.setString(1, valorTroca);
            }
            
            
            ResultSet result = query.executeQuery();
            
            if(result == null){
                return;
            }
            
            /** Montando JTable */
            DefaultTableModel modeloTabela = (DefaultTableModel) jTableRios.getModel();
            
            // Limpando registros
            modeloTabela.setRowCount(0);
            this.Dados.clear();

            while(result.next()) {
                modeloTabela.addRow(new String[] {  
                        String.valueOf(result.getInt("_ID")),
                        result.getString("Nome"),
                        result.getString("Localidade"),
                        result.getString("Nascente"),
                        
                    }); 
                
                Rio newRio = new Rio();
                newRio.id = result.getInt("_ID");
                newRio.Nome = result.getString("Nome");                
                newRio.Localidade = result.getString("Localidade");
                newRio.Nascente = result.getString("Nascente");
                newRio.Acao = "";
                this.Dados.add(newRio);
            }

            jTableRios.setModel(modeloTabela);
            result.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar rio.\n\n" + ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btn_LocalizarMouseClicked

    private void AtualizarJTableFromDados(){
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableRios.getModel();
            
        // Limpando registros
        modeloTabela.setRowCount(0);
        
        for(Rio rio : this.Dados){
            modeloTabela.addRow(new String[] {
                String.valueOf(rio.id),
                rio.Nome,
                rio.Localidade,
                rio.Nascente,
            });
        }
        
        jTableRios.setModel(modeloTabela);
    }
    
    private void ComboBoxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFiltroActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        CadastroRio cad = new CadastroRio();
        cad.setVisible(true);
        
        cad.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if(cad.NewRio != null){
                    cad.NewRio.id = 0;
                    cad.NewRio.Acao = "I";
                    Dados.add(cad.NewRio);
                    AtualizarJTableFromDados();
                }                
            }
        });
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String SQL = ""; 
        for(Rio rio : this.Dados){
            try{
                
                switch(rio.Acao){
                    case "I":
                        /** Monta o Insert do Rio */ 
                        SQL = "INSERT INTO Rio (Nome, Localidade, Nascente) VALUES ( ";
                        SQL += "    '" + rio.Nome + "' ,";
                        SQL += "    '" + rio.Localidade + "' ,";
                        SQL += "    '" + rio.Nascente + "'  )";
                        PreparedStatement pstm = ConexaoDB.getNewPreparedStatement(SQL);
//                        pstm.setString(1, rio.Nome);
//                        pstm.setString(2, rio.Localidade);
//                        pstm.setString(3, rio.Nascente);
                        pstm.execute();
                        pstm.close();
                        break;

                    case "A":
                        /** Monta o Update do Rio */ 
                        SQL = "UPDATE Rio";
                        SQL += "    SET Nome = '" + rio.Nome + "'";
                        SQL += "       ,Localidade = '" + rio.Localidade + "'";
                        SQL += "       ,Nascente = '" + rio.Nascente + "'";
                        SQL += "    WHERE Rio._ID = ?";
                        pstm = ConexaoDB.getNewPreparedStatement(SQL);
//                        pstm.setString(1, rio.Nome);                        
//                        pstm.setString(2, rio.Localidade);
//                        pstm.setString(3, rio.Nascente);
                        pstm.setInt(1, rio.id);
                        pstm.execute();
                        pstm.close();
                        break;

                    case "D":
                        /** Monta o Delete do Rio */ 
                        SQL = "DELETE FROM Rio ";
                        SQL += "WHERE _ID = ?";
                        pstm = ConexaoDB.getNewPreparedStatement(SQL);
                        pstm.setInt(1, rio.id);
                        pstm.execute();
                        pstm.close();
                        break;
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro na ação '"+ rio.Acao +"' do rio "
                        + rio.id + " - " + rio.Nome + ". Motivo: " + e.getMessage());
                return;
            }
        }
        
        JOptionPane.showMessageDialog(null,"Alterações salvas com sucesso.");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_AlteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AlteracaoMouseClicked
        // TODO add your handling code here:
        AlteracaoRio alt = new AlteracaoRio();
        alt.SetRio(this.Dados.get(jTableRios.getSelectedRow()));
        alt.setVisible(true);
        
        alt.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                AtualizarJTableFromDados();
            }
        });
    }//GEN-LAST:event_btn_AlteracaoMouseClicked

    private void btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseClicked
        if(jTableRios.getSelectedRow() < 0){
            return;            
        }
        
        this.Dados.get(jTableRios.getSelectedRow()).Acao = "D";
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableRios.getModel();
        modeloTabela.removeRow(jTableRios.getSelectedRow());
    }//GEN-LAST:event_btn_DeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                    
                }
                
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoRio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoRio().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxFiltro;
    private javax.swing.JButton btn_Alteracao;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Localizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRios;
    private javax.swing.JTextField txt_Busca;
    // End of variables declaration//GEN-END:variables
}
